// lightning-share.js — generated by Lightning for Notes
(function() {
  'use strict';
  if (!window.lightning) return;

  window.lightning.share = {
    version: '0.1.0',

    isAvailable: function() {
      return !!(navigator.share);
    },

    canShare: function(data) {
      return !!(navigator.share && navigator.canShare && navigator.canShare(data));
    },

    // data: { title?, text?, url?, files?: File[] }
    share: function(data) {
      if (!navigator.share) return Promise.reject(new Error('Web Share API not supported'));
      return navigator.share(data);
    }
  };
})();