// lightning-motion.js — generated by Lightning for Notes
(function() {
  'use strict';
  if (!window.lightning) return;

  window.lightning.motion = {
    version: '0.1.0',

    isAvailable: function() {
      return typeof DeviceMotionEvent !== 'undefined'
          || typeof DeviceOrientationEvent !== 'undefined';
    },

    // iOS 13+ requires explicit permission request
    // Returns Promise<'granted'|'denied'>
    requestPermission: function() {
      if (typeof DeviceMotionEvent !== 'undefined'
          && typeof DeviceMotionEvent.requestPermission === 'function') {
        return DeviceMotionEvent.requestPermission();
      }
      // Android / desktop — permission not required
      return Promise.resolve('granted');
    },

    // callback receives { alpha, beta, gamma, absolute }
    // Returns unsubscribe function
    onOrientation: function(callback) {
      window.addEventListener('deviceorientation', callback);
      return function() { window.removeEventListener('deviceorientation', callback); };
    },

    // callback receives { acceleration, accelerationIncludingGravity, rotationRate, interval }
    // Returns unsubscribe function
    onMotion: function(callback) {
      window.addEventListener('devicemotion', callback);
      return function() { window.removeEventListener('devicemotion', callback); };
    }
  };
})();