// lightning.js — generated by Lightning for Notes
(function() {
  'use strict';

  // Platform detection
  var _isNative = typeof window.__LIGHTNING_NATIVE__ !== 'undefined';
  var _ua = navigator.userAgent;
  var _isIOS = /iPad|iPhone|iPod/.test(_ua) && !window.MSStream;
  var _isMacOS = /Macintosh/.test(_ua);

  // ---- IndexedDB helpers ----

  function openKvStore() {
    return new Promise(function(resolve, reject) {
      var req = indexedDB.open('notes-lightning-kv', 1);
      req.onupgradeneeded = function(e) {
        e.target.result.createObjectStore('kv', { keyPath: 'k' });
      };
      req.onsuccess = function(e) { resolve(e.target.result); };
      req.onerror = function(e) { reject(e.target.error); };
    });
  }

  function openCollectionStore(name) {
    return new Promise(function(resolve, reject) {
      var req = indexedDB.open('notes-lightning-col-' + name, 1);
      req.onupgradeneeded = function(e) {
        e.target.result.createObjectStore('docs', { keyPath: 'id' });
      };
      req.onsuccess = function(e) { resolve(e.target.result); };
      req.onerror = function(e) { reject(e.target.error); };
    });
  }

  function uid() {
    return Date.now().toString(36) + Math.random().toString(36).slice(2, 9);
  }

  // ---- window.lightning ----
  window.lightning = {
    version: '0.1.0',
    platform: {
      isNative: _isNative,
      isIOS: _isIOS,
      isMacOS: _isMacOS,
      userAgent: _ua
    },
    data: {
      get: function(key) {
        return openKvStore().then(function(db) {
          return new Promise(function(resolve, reject) {
            var tx = db.transaction('kv', 'readonly');
            var req = tx.objectStore('kv').get(key);
            req.onsuccess = function(e) {
              resolve(e.target.result ? e.target.result.v : null);
            };
            req.onerror = function(e) { reject(e.target.error); };
          });
        });
      },
      set: function(key, value) {
        return openKvStore().then(function(db) {
          return new Promise(function(resolve, reject) {
            var tx = db.transaction('kv', 'readwrite');
            var req = tx.objectStore('kv').put({ k: key, v: value });
            req.onsuccess = function() { resolve(); };
            req.onerror = function(e) { reject(e.target.error); };
          });
        });
      },
      delete: function(key) {
        return openKvStore().then(function(db) {
          return new Promise(function(resolve, reject) {
            var tx = db.transaction('kv', 'readwrite');
            var req = tx.objectStore('kv').delete(key);
            req.onsuccess = function() { resolve(); };
            req.onerror = function(e) { reject(e.target.error); };
          });
        });
      },
      keys: function() {
        return openKvStore().then(function(db) {
          return new Promise(function(resolve, reject) {
            var tx = db.transaction('kv', 'readonly');
            var req = tx.objectStore('kv').getAllKeys();
            req.onsuccess = function(e) { resolve(e.target.result); };
            req.onerror = function(e) { reject(e.target.error); };
          });
        });
      },
      collection: function(name) {
        return {
          insert: function(doc) {
            return openCollectionStore(name).then(function(db) {
              return new Promise(function(resolve, reject) {
                var record = Object.assign({}, doc, { id: uid() });
                var tx = db.transaction('docs', 'readwrite');
                var req = tx.objectStore('docs').add(record);
                req.onsuccess = function() { resolve(record); };
                req.onerror = function(e) { reject(e.target.error); };
              });
            });
          },
          find: function(query) {
            return openCollectionStore(name).then(function(db) {
              return new Promise(function(resolve, reject) {
                var tx = db.transaction('docs', 'readonly');
                var req = tx.objectStore('docs').getAll();
                req.onsuccess = function(e) {
                  var docs = e.target.result;
                  if (query) {
                    docs = docs.filter(function(doc) {
                      return Object.keys(query).every(function(k) {
                        return doc[k] === query[k];
                      });
                    });
                  }
                  resolve(docs);
                };
                req.onerror = function(e) { reject(e.target.error); };
              });
            });
          },
          findById: function(id) {
            return openCollectionStore(name).then(function(db) {
              return new Promise(function(resolve, reject) {
                var tx = db.transaction('docs', 'readonly');
                var req = tx.objectStore('docs').get(id);
                req.onsuccess = function(e) { resolve(e.target.result || null); };
                req.onerror = function(e) { reject(e.target.error); };
              });
            });
          },
          update: function(id, updates) {
            var self = this;
            return self.findById(id).then(function(existing) {
              if (!existing) { return Promise.reject(new Error('Document not found: ' + id)); }
              return openCollectionStore(name).then(function(db) {
                return new Promise(function(resolve, reject) {
                  var updated = Object.assign({}, existing, updates, { id: id });
                  var tx = db.transaction('docs', 'readwrite');
                  var req = tx.objectStore('docs').put(updated);
                  req.onsuccess = function() { resolve(updated); };
                  req.onerror = function(e) { reject(e.target.error); };
                });
              });
            });
          },
          delete: function(id) {
            return openCollectionStore(name).then(function(db) {
              return new Promise(function(resolve, reject) {
                var tx = db.transaction('docs', 'readwrite');
                var req = tx.objectStore('docs').delete(id);
                req.onsuccess = function() { resolve(); };
                req.onerror = function(e) { reject(e.target.error); };
              });
            });
          },
          clear: function() {
            return openCollectionStore(name).then(function(db) {
              return new Promise(function(resolve, reject) {
                var tx = db.transaction('docs', 'readwrite');
                var req = tx.objectStore('docs').clear();
                req.onsuccess = function() { resolve(); };
                req.onerror = function(e) { reject(e.target.error); };
              });
            });
          },
          count: function() {
            return openCollectionStore(name).then(function(db) {
              return new Promise(function(resolve, reject) {
                var tx = db.transaction('docs', 'readonly');
                var req = tx.objectStore('docs').count();
                req.onsuccess = function(e) { resolve(e.target.result); };
                req.onerror = function(e) { reject(e.target.error); };
              });
            });
          }
        };
      }
    }
  };
})();