// lightning-media.js — generated by Lightning for Notes
(function() {
  'use strict';
  if (!window.lightning) return;

  var _streams = [];

  window.lightning.media = {
    version: '0.1.0',

    isAvailable: function() {
      return !!(navigator.mediaDevices && navigator.mediaDevices.getUserMedia);
    },

    // constraints: { audio?: bool|object, video?: bool|object }
    // Returns Promise<MediaStream>
    requestStream: function(constraints) {
      if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) {
        return Promise.reject(new Error('MediaDevices not supported'));
      }
      return navigator.mediaDevices.getUserMedia(
        constraints || { audio: true, video: true }
      ).then(function(stream) {
        _streams.push(stream);
        return stream;
      });
    },

    // Request audio-only stream
    requestAudio: function() {
      return this.requestStream({ audio: true, video: false });
    },

    // Request video-only stream
    requestVideo: function(facingMode) {
      return this.requestStream({
        audio: false,
        video: facingMode ? { facingMode: facingMode } : true
      });
    },

    // Stop all tracks on a stream (or all active streams if none passed)
    stopStream: function(stream) {
      if (stream) {
        stream.getTracks().forEach(function(t) { t.stop(); });
        _streams = _streams.filter(function(s) { return s !== stream; });
      } else {
        _streams.forEach(function(s) {
          s.getTracks().forEach(function(t) { t.stop(); });
        });
        _streams = [];
      }
    },

    // Returns Promise<MediaDeviceInfo[]>
    enumerateDevices: function() {
      if (!navigator.mediaDevices || !navigator.mediaDevices.enumerateDevices) {
        return Promise.resolve([]);
      }
      return navigator.mediaDevices.enumerateDevices();
    },

    // Convenience: get list of cameras only
    getCameras: function() {
      return this.enumerateDevices().then(function(devices) {
        return devices.filter(function(d) { return d.kind === 'videoinput'; });
      });
    }
  };
})();