// lightning-wake.js — generated by Lightning for Notes
(function() {
  'use strict';
  if (!window.lightning) return;

  var _lock = null;

  function reacquire() {
    if (document.visibilityState === 'visible' && _lock === null) {
      navigator.wakeLock.request('screen').then(function(lock) {
        _lock = lock;
        lock.addEventListener('release', function() { _lock = null; });
      }).catch(function() {});
    }
  }

  window.lightning.wake = {
    version: '0.1.0',

    isAvailable: function() {
      return !!('wakeLock' in navigator);
    },

    // Lock screen on — auto re-acquires after visibility change
    lock: function() {
      if (!('wakeLock' in navigator)) return Promise.reject(new Error('Wake Lock not supported'));
      return navigator.wakeLock.request('screen').then(function(lock) {
        _lock = lock;
        lock.addEventListener('release', function() { _lock = null; });
        document.addEventListener('visibilitychange', reacquire);
        return lock;
      });
    },

    unlock: function() {
      document.removeEventListener('visibilitychange', reacquire);
      if (_lock) {
        var p = _lock.release();
        _lock = null;
        return p;
      }
      return Promise.resolve();
    },

    isActive: function() {
      return _lock !== null;
    }
  };
})();