// lightning-ui.js — generated by Lightning for Notes
(function() {
  'use strict';

  var style = document.createElement('style');
  style.textContent = [
    '.lg-glass {',
    '  background: rgba(255,255,255,0.01);',
    '  backdrop-filter: blur(28px) saturate(3.2) brightness(1.12) contrast(0.95);',
    '  -webkit-backdrop-filter: blur(28px) saturate(3.2) brightness(1.12) contrast(0.95);',
    '  border: 0.5px solid rgba(255,255,255,0.18);',
    '  box-shadow:',
    '    inset 0 1px 0 rgba(255,255,255,0.60),',
    '    inset 0 -0.5px 0 rgba(0,0,0,0.10),',
    '    0 4px 24px rgba(0,0,0,0.14);',
    '  color: rgba(255,255,255,0.90);',
    '  transition: transform 0.18s cubic-bezier(0.34,1.56,0.64,1), opacity 0.15s ease;',
    '}',
    '.lg-glass:active {',
    '  transform: scale(0.96);',
    '  opacity: 0.78;',
    '}',
    '[data-theme="light"] .lg-glass {',
    '  background: rgba(255,255,255,0.18);',
    '  backdrop-filter: blur(24px) saturate(2.2) brightness(1.04);',
    '  -webkit-backdrop-filter: blur(24px) saturate(2.2) brightness(1.04);',
    '  border: 0.5px solid rgba(255,255,255,0.55);',
    '  box-shadow:',
    '    inset 0 1px 0 rgba(255,255,255,0.95),',
    '    inset 0 -0.5px 0 rgba(0,0,0,0.06),',
    '    0 2px 12px rgba(0,0,0,0.06);',
    '  color: rgba(0,0,0,0.72);',
    '}'
  ].join('\n');
  document.head.appendChild(style);

  // Expose window.lightning.ui namespace
  if (window.lightning) {
    window.lightning.ui = {
      version: '0.1.0',
      applyGlass: function(el) {
        el.classList.add('lg-glass');
        return el;
      }
    };
  }

  // Native overlay: replace lg-glass elements with real SwiftUI views.
  async function mountNativeElements() {
    if (!window.lightning) return;
    var buttons = document.querySelectorAll('.lg-glass');
    for (var i = 0; i < buttons.length; i++) {
      var btn = buttons[i];
      var r = btn.getBoundingClientRect();
      var id = 'lg-native-' + i;
      try {
        await window.lightning.invoke('ui.mountNative', {
          id: id,
          label: btn.textContent.trim(),
          rect: { x: r.x, y: r.y, width: r.width, height: r.height },
          webViewHeight: window.innerHeight
        });
        btn.style.opacity = '0';
      } catch(e) {
        // Fallback to CSS — element stays visible with glass styles.
      }
    }
  }

  // Observe future lg-glass elements added to DOM.
  var lgObserver = new MutationObserver(function() {
    mountNativeElements();
  });
  lgObserver.observe(document.body || document.documentElement, {
    childList: true,
    subtree: true
  });

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', mountNativeElements);
  } else {
    mountNativeElements();
  }
})();